# Default values for application.
environment: dev
api:
  appName: api
  image: hmbdevopsteam.azurecr.io/webapibackend:3367
  port: 80
  type: ClusterIP

ingress:
  secretName: tls-secret
  hostName: hmb-dev-ops-app-dev.eastus.cloudapp.azure.com
  certificateOwnerEmail: pjb2@hmbnet.com