apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Values.api.appName }}
  labels:
    app: {{ .Values.api.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.api.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.api.appName }}
    spec:
{{ if .Values.image.private }}
      imagePullSecrets:
        - name: {{ .Chart.Name }}-acr-secret
{{ end }}
      containers:
        - name: {{ .Values.api.appName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - containerPort: {{ .Values.api.port | default 80 }}
          env:
          - name: APP_ENVIRONMENT
            value: {{ .Values.environment }}
